/**
 * @file pwm.h
 * @brief Control for PWM signals generated by the micro on up to four channels.
 * @note
 * General steps for use:
 *   0. Choose a base frequency.
 *   1. Initialize the timer              (hal_pwm_timer_init())
 *   2. Initialize each desired channel   (hal_pwm_channel_init())
 *   3. Enable the channel output         (hal_pwm_enable())
 *   4. Set the duty cycle                (hal_pwm_set_duty_cycle())
 *
 * All four channels share the same base frequency set in step 1.
 * Each channel's duty cycle is independent. Channels may be brought up
 * one at a time in any order after the timer is initialized.
 *
 * Copyright (c) 2025 Cory McKiel.
 * Licensed under the MIT License. See LICENSE file in the project root.
 */
#ifndef _PWM_H
#define _PWM_H

#include <stdbool.h>
#include "hal_types.h"

/**
 * @brief Channel select type
 */
typedef enum {
  _HAL_PWM_CH_MIN,
  HAL_PWM_CH1 = _HAL_PWM_CH_MIN,
  HAL_PWM_CH2,
  HAL_PWM_CH3,
  HAL_PWM_CH4,
  _HAL_PWM_CH_MAX
} hal_pwm_channel_t;

/**
 * @brief Initializes the hardware timer (TIM1) for PWM output at the given base frequency.
 *        Must be called once before initializing any channel. All channels share this frequency.
 *
 * @param pwm_frequency_hz The base frequency in Hz (e.g. 20000 for 20 kHz).
 *
 * @return HAL_STATUS_OK on success.
 */
hal_status_t hal_pwm_timer_init(uint32_t pwm_frequency_hz);

/**
 * @brief Initializes a single PWM channel. Configures the GPIO pin and channel output registers.
 *        hal_pwm_timer_init() must be called before this. Channels may be initialized in any order.
 *
 * @param channel The channel to bring up.
 *
 * @return HAL_STATUS_OK on success.
 */
hal_status_t hal_pwm_channel_init(hal_pwm_channel_t channel);

/**
 * @brief Enables or disables a channel's output. When disabled the pin is held low.
 *
 * @param channel The channel to enable or disable.
 * @param enable  true to enable, false to disable.
 */
void hal_pwm_enable(hal_pwm_channel_t channel, bool enable);

/**
 * @brief Sets the duty cycle 0% - 100% for one channel. The channel must be enabled first.
 *
 * @param channel The target channel.
 * @param percent 0 through 100.
 */
void hal_pwm_set_duty_cycle(hal_pwm_channel_t channel, uint8_t percent);

/**
 * @brief Changes the base PWM frequency shared by all channels. The duty-cycle ratio of every
 *        enabled channel is preserved by rescaling its compare register.
 *
 * @param pwm_frequency_hz New frequency in Hz (e.g. 20000 for 20 kHz).
 */
void hal_pwm_set_frequency(uint32_t pwm_frequency_hz);

#endif /* _PWM_H */
