/**
 * @file pwm.h
 * @brief Control for a PWM signal generated by the micro.
 * @note
 * General steps for use:
 *   0. Choose a frequency.
 *   1. Initialize pwm driver (hal_pwm_init())
 *   2. Enable the output     (hal_pwm_enable())
 *   3. Set duty cycle        (hal_pwm_set_duty_cycle())
 *
 * At this point a PWM signal of your chosen frequency and
 * duty cycle is being output to pin.
 *
 * Copyright (c) 2025 Cory McKiel.
 * Licensed under the MIT License. See LICENSE file in the project root.
 */
#ifndef _PWM_H
#define _PWM_H

#include <stdbool.h>
#include "hal_types.h"

/**
 * @brief Initializes all the hardware (GPIO, TIMER, and CHANNEL) to deliver a PWM signal.
 *
 * @param pwm_frequency_hz The frequency of the PWM signal you would like generated in Hz. eg for 20kHz -> 20,000.
 *
 * @return HAL_STATUS_OK on success.
 */
hal_status_t hal_pwm_init(uint32_t pwm_frequency_hz);

/**
 * @brief enable or disable the pwm signal. If disabled, nothing will show up on pins.
 *
 * @param enable true to enable the driver, false to disable.
 */
void hal_pwm_enable(bool enable);

/**
 * @brief Sets the duty cycle 0% - 100% for the PWM signal.
 *
 * @param percent Takes the values 0 through 100 as integers to express the desired DC.
 */
void hal_pwm_set_duty_cycle(uint8_t percent);

/**
 * @brief Sets the PWM signal frequency to a new value after the driver has already been initialized.
 *
 * @param pwm_frequency_hz The frequency of the PWM signal you would like generated in Hz. eg for 20kHz -> 20,000.
 */
void hal_pwm_set_frequency(uint32_t pwm_frequency_hz);

#endif /* _PWM_H */
